Document: hprd
Title: Debian hprd Manual
Author: <insert document author here>
Abstract: This manual describes what hprd is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/hprd/hprd.sgml.gz

Format: postscript
Files: /usr/share/doc/hprd/hprd.ps.gz

Format: text
Files: /usr/share/doc/hprd/hprd.text.gz

Format: HTML
Index: /usr/share/doc/hprd/html/index.html
Files: /usr/share/doc/hprd/html/*.html
